name: sidd_bot_jules

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: "Task for Jules"
        required: true
        type: string

jobs:
  sidd_bot_jules:
    runs-on: ubuntu-latest

    steps:
      - name: Run sidd_bot_jules
        uses: google-labs-code/jules-action@main
        with:
          prompt: ${{ inputs.prompt }}
          jules_api_key: ${{ secrets.JULES_API_KEY }}
          starting_branch: main
          include_last_commit: true
          include_commit_log: true
